Sprint 1
ClevertecFrontendLab/sprint1-sveta-confeta pull request #1
Opened 2023-02-01 21:56 UTC by sveta-confeta

2023-02-01 21:59 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 6.
Количество непройденных тестов: 6.
***
**Test width 1440px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675288782/Test%20width%201440px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 1440px -- test layout content view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675288782/Test%20width%201440px%20--%20test%20layout%20content%20view%20(failed).png)
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675288782/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 320px -- test layout content view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675288782/Test%20width%20320px%20--%20test%20layout%20content%20view%20(failed).png)
***
**Test width 768px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675288782/Test%20width%20768px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 768px -- test layout content view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675288782/Test%20width%20768px%20--%20test%20layout%20content%20view%20(failed).png)

2023-02-01 22:34 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 6.
Количество непройденных тестов: 6.
***
**Test width 1440px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675290857/Test%20width%201440px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 1440px -- test layout content view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675290857/Test%20width%201440px%20--%20test%20layout%20content%20view%20(failed).png)
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675290857/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 320px -- test layout content view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675290857/Test%20width%20320px%20--%20test%20layout%20content%20view%20(failed).png)
***
**Test width 768px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675290857/Test%20width%20768px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 768px -- test layout content view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675290857/Test%20width%20768px%20--%20test%20layout%20content%20view%20(failed).png)

2023-02-02 05:47 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675316854/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675316854/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675316854/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675316854/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675316854/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675316854/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675316854/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675316854/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675316854/content-window.png)

2023-02-02 06:32 UTC, Gaurrus requested changes
замарочка с svg лишняя - можно просто импортировать как обычную картинку и так же всталять в img

2023-02-02 06:32 UTC, Gaurrus commented on .eslintrc.js
>          'import/no-default-export': 'error',
![image](https://user-images.githubusercontent.com/85307211/216248108-b6fbe117-df04-4722-8a37-86e57841f3a0.png)
отступ надо поправить и перепроверить шрифт кнопки для всех экранов, вроде не хватает жирности

2023-02-02 07:31 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675323068/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675323068/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675323068/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675323068/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675323068/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675323068/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675323068/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675323068/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/sveta-confeta/1675323068/content-window.png)

2023-02-02 07:35 UTC, Gaurrus approved these changes

2023-02-02 07:46 UTC, merged